---
- name: Using our new module
  hosts: localhost

  collections:
          - buzzaldrin.apollo

  tasks:
  - name: New module
    my_new_test_module:
      name: Zach
      augment: true
    register: results

  - debug:
      var: results

