---
- name: Playbook with Precheck Role
  hosts: ~^arista
  gather_facts: yes
  connection: network_cli
  become: yes
  become_method: enable

  tasks:
  - name: Import the precheck role
    import_role:
      name: alta3.aristaeos.precheck
